### ISSUE TITLE
GAE Calendar (Java, Spring MVC, JPA, jQuery, Datastore vs Cloud SQL)

### ISSUE THREAD

**Issue by invaa** [GoogleCloudPlatform/Template#10]
Hello!

I'd like to submit a calendar app written in Java and demonstrating the usage of GAE. The technology stack is: Java, Spring MVC, JPA, jQuery and both Google Cloud Datastore and Google Cloud SQL.

Code for the project is here: 
1. Cloud SQL version: https://github.com/invaa/CloudCalendar/tree/spring-cloud-sql
2. Datastore version: https://github.com/invaa/CloudCalendar/tree/spring-data-v2

Demo is running here: http://cloudcalendarservice.appspot.com/

I'm looking forward to your review. Thanks in advance.

**Comment by schabiyo** [comment]
Good job, I do however have a question. Is it possible to create a custom repository 9Spring Data) for DataStore whitch can be used within an application outside Gae?

Thjanks in advance

**Comment by invaa** [comment]
Hello, schabiyo! Thanks for the question.

Using DataNucleus library (just as in the provided sources) you can create custom repositories as well.

Here is the info on custom repos:
http://docs.spring.io/spring-data/data-commons/docs/1.6.1.RELEASE/reference/html/repositories.html

Although, some JPA limitations do exist, they are not related to Spring Data custom repositories. Here is more info on JPA limitations:
https://cloud.google.com/appengine/docs/java/datastore/jpa/overview-dn2

**Comment by schabiyo** [comment]
Hello invaa,
Thanks for the quickl reply. I will give it a try. One last question, to witch JPA limitation were you refering to? Is it something than can prevent me from reaching my target?

Thanks again,

**Comment by invaa** [comment]
No it shouldn't. But I mentioned it just to let you know that DataNuleus JPA implementation for Google Cloud Datastore has some limitations and it's important to keep it in mind.
