### ISSUE TITLE
Sample AppEngine Websocket Nodejs

### ISSUE THREAD

**Issue by thebergamo** [GoogleCloudPlatform/Template#12]
This is a small example for using websocket and nodejs on the App Engine.

This is the project: https://github.com/marcosbergamo/appengine-websocket-nodejs

(A little question: How I can send the pull request to send my repo for GoogleCloudPlatform?)

**Comment by thebergamo** [comment]
My Sample app are not accept?

**Comment by elibixby** [comment]
See my response on issue #14

**Comment by thebergamo** [comment]
Oh sorry! I don't saw this issue. I'll waiting...
