### ISSUE TITLE
New AppEngine Play Framework / Scala sample application

### ISSUE THREAD

**Issue by taraxe** [GoogleCloudPlatform/Template#14]
Hi,

Here is a proposal for an [AppEngine Play Framework / Scala sample application](https://github.com/taraxe/gcloud-play-sample) using custom runtime with managed VMs.

Cheers,
Antoine

**Comment by M13Kd** [comment]
Use any repository except Gnarly so that fork my BEDROCK REPOSITORIES MASTER ROOT YOUR CHOICE.  KEEP IN TOUCH. 

-------- Original message --------

**Comment by taraxe** [comment]
No interest?

**Comment by elibixby** [comment]
It's an interesting proposal, we've decided this is no longer the place we want to take sample repository requests. We'll track internally, and soon have a new place for these requests! Thanks!

**Comment by taraxe** [comment]
Okay, thank you for the feedback
