### ISSUE TITLE
Create branches with different README for each project

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/Template#18]
@jeffmendoza

**Comment by tmatsuo** [comment]
or, is it ok with having multiple README template with postfix?

For example

readme.md.appengine
readme.md.snippets
readme.md.compute

?

**Comment by elibixby** [comment]
I think it's preferable to have it in branches as then we don't have to do extra work after cloning.

**Comment by tmatsuo** [comment]
ah, good point

**Comment by nishankbhati** [comment]
Do your project need documentation? I am ready to do it in my summers.

**Comment by webmaven** [comment]
@elibixby, does this still need to be done?

**Comment by elibixby** [comment]
I'm not sure this is relevant since we've moved to megarepos.

**Comment by raulvelasco75** [comment]
-Hello thank you so much for writing me can you Help me please
warm regards.
Raul.

2016-07-06 14:03 GMT-05:00 elibixby <notifications@github.com>:
