### ISSUE TITLE
New appengine-python-morepath-skeleton app

### ISSUE THREAD

**Issue by webmaven** [GoogleCloudPlatform/Template#7]
I have created a skeleton app (analogous to the [Flask skeleton](https://github.com/GoogleCloudPlatform/appengine-python-flask-skeleton)) for the [Morepath](http://morepath.readthedocs.org/en/latest/) framework. This uncovered an issue with the way the ```lib/``` directory is set up in the other Python skeletons (I've submitted a [PR for the Flask skeleton](https://github.com/GoogleCloudPlatform/appengine-python-flask-skeleton/pull/9) so far, and if that goes well, I'll do it for the Bottle skeleton as well).

The current code for my Morepath skeleton is here: 
https://github.com/webmaven/appengine-python-morepath-skeleton
And is running here: http://morepath-gae.appspot.com/

Anyway, I think having a skeleton for an additional Python framework would be helpful and instructive. I can also work on a similar skeleton using the [Pyramid framework](http://www.pylonsproject.org/projects/pyramid/about), and possibly some others.

**Comment by webmaven** [comment]
@elibixby, why close the issue?

**Comment by elibixby** [comment]
See my comment on #14 

Not a comment on these projects. This is just not where we'd like it to happen in the future. =)
